{{-range $name, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $service.image.repository }}:{{ $service.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: {{ $service.port }}
          resources:
            {{-toYaml $.Values.resources | nindent 12 }}
          {{-if $.Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $.Values.probes.liveness.path }}
              port: {{ $.Values.probes.liveness.port }}
            initialDelaySeconds: {{ $.Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ $.Values.probes.readiness.path }}
              port: {{ $.Values.probes.readiness.port }}
            initialDelaySeconds: {{ $.Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ $.Values.probes.readiness.periodSeconds }}
          {{-end }}
{{-end }}

