replicaCount: 1

# Chính sách pull image
image:
  pullPolicy: IfNotPresent
environment:
  NODE_ENV: development

# Danh sách service trong microservice app
services:
  api-gateway:
    replicaCount: 1
    port: 3000
    type: NodePort
    image:
      repository: fintechdevopsacr123ntech-f4aadcc8c4f2daaa.azurecr.io/api-gateway
      tag: v32

  auth-service:
    replicaCount: 1
    port: 3001
    image:
      repository: fintechdevopsacr123ntech-f4aadcc8c4f2daaa.azurecr.io/auth-service
      tag: v32

  charge-service:
    replicaCount: 1
    port: 3002
    image:
      repository: fintechdevopsacr123ntech-f4aadcc8c4f2daaa.azurecr.io/charge-service
      tag: v34

  history-service:
    replicaCount: 1
    port: 3003
    image:
      repository: fintechdevopsacr123ntech-f4aadcc8c4f2daaa.azurecr.io/history-service
      tag: v34

  transaction-service:
    replicaCount: 1
    port: 3004
    image:
      repository: fintechdevopsacr123ntech-f4aadcc8c4f2daaa.azurecr.io/transaction-service
      tag: v33